name: Java CI

on:
  schedule:
    - cron: "0 13 * * *"
  push:
    branches:
      - master
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -q clean compile exec:java
        env:
          CLIENT_ID: ${{secrets.CLIENT_ID}}
          CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
          REFRESH_TOKEN: ${{secrets.REFRESH_TOKEN}}
          PLAYLIST_ID: ${{secrets.PLAYLIST_ID}}
